Update patch set 8
Patch Set 8:

Gitlab Azure AKS 4: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//122463-8/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 23
 * Nb Failed Jobs: 1
 * List of Failed Jobs: [
   - onap-netbox-app-provisioning]
 * Nb Deployments: 139
 * Nb Failed Deployments: 2
 * List of Failed Deployments: [
   - onap-modeling-etsicatalog
   - onap-netbox-app]
 * Nb StatefulSets: 24
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 65
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 36
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-msb]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2021-07-13 13:37:15,201 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DCAE Microservices Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /iui/microservices/default.html (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480ed0110>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/multicloud/v0/swagger.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480f31350>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/multicloud-pike/v0/swagger.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480f0abd0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/multicloud-k8s/v1/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480e95410>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /iui/usecaseui/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480e351d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/gvnfmdriver/v1/health_check (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480f07990>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/huaweivnfmdriver/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480e38e10>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/nslcm/v1/health_check (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480dd5b50>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/vnflcm/v1/health_check (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480de2d90>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/vnfmgr/v1/health_check (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480f0ad50>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/vnfres/v1/health_check (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480df5cd0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/ztevnfmdriver/v1/health_check (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480df8390>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/holmes-rule-mgmt/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480d9da50>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/holmes-engine-mgmt/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480df8710>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/multicloud-fcaps/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480dcad90>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/parser/v1/health_check (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb480db5c10>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
41 critical tests, 25 passed, 16 failed
41 tests total, 25 passed, 16 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | PASS |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | PASS |
--------> CMPv2 tests
Deploying VES Client :: This test case deploys VES Client with "en... | PASS |
Deploying VES collector with CMPv2 :: This test case deploys secon... | PASS |
Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | PASS |
Send registration request to CMPv2 VES :: This test case triggers ... | PASS |
Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
Send registration request to VES without CMPv2 certificate :: This... | PASS |
Cmpv2 :: CMPv2 Usecase functionality                                  | PASS |
--------> DCAEMOD tests
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | PASS |
--------> Basic Onboard tests (SDC)
basic_onboard: PASS (01:41)
--------> CDS tests
basic_cds: PASS (00:14)

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
--------> 5gbulkpm tests
5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
--------> basic_vm tests
basic_vm: FAIL (09:20)
--------> basic_network tests
basic_network: PASS (05:40)
--------> basic_cnf tests
basic_cnf: FAIL (06:21)
--------> basic_vm_macro tests
basic_vm_macro: PASS (11:01)
--------> basic_clamp tests
basic_clamp: PASS (04:53)
--------> pnf_macro tests
pnf_macro: FAIL (04:33)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> nonssl_endpoints tests NOT executed
--------> jdpw_ports tests NOT executed
--------> kube_hunter tests NOT executed
--------> root_pods tests NOT executed
--------> unlimitted_pods tests NOT executed

____________________________________________________________

Patch-set: 8