Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//96250-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 182
 * Nb Failed Pods: 85
 * List of Failed Pods: [
   - onap-aaf-aaf-cm-788f96b74b-btctz
   - onap-aaf-aaf-oauth-797569bfd6-htg9g
   - onap-aaf-aaf-sms-74975b77f-4rk78
   - onap-aai-aai-67b4f7cfdc-47r96
   - onap-aai-aai-graphadmin-6c5544c67c-mppb8
   - onap-aai-aai-resources-5955466f6f-9jwbj
   - onap-aai-aai-sparky-be-68bcf7c4c-2dmgl
   - onap-aai-aai-traversal-7f77cb867c-qp8zb
   - onap-appc-appc-cdt-7645f5dcd7-2hw86
   - onap-appc-appc-cdt-7645f5dcd7-4lbxw
   - onap-appc-appc-cdt-7645f5dcd7-4phh6
   - onap-appc-appc-cdt-7645f5dcd7-6r27g
   - onap-appc-appc-cdt-7645f5dcd7-6sxdg
   - onap-appc-appc-cdt-7645f5dcd7-6wl4w
   - onap-appc-appc-cdt-7645f5dcd7-87tbs
   - onap-appc-appc-cdt-7645f5dcd7-8lcbt
   - onap-appc-appc-cdt-7645f5dcd7-bsmb2
   - onap-appc-appc-cdt-7645f5dcd7-c2jvs
   - onap-appc-appc-cdt-7645f5dcd7-h4zs2
   - onap-appc-appc-cdt-7645f5dcd7-h8tzn
   - onap-appc-appc-cdt-7645f5dcd7-hlnz8
   - onap-appc-appc-cdt-7645f5dcd7-jxhfv
   - onap-appc-appc-cdt-7645f5dcd7-lhs5b
   - onap-appc-appc-cdt-7645f5dcd7-mr849
   - onap-appc-appc-cdt-7645f5dcd7-rs8nq
   - onap-appc-appc-cdt-7645f5dcd7-v8bb8
   - onap-appc-appc-cdt-7645f5dcd7-vlcsz
   - onap-cds-cds-sdc-listener-75c5fd5ffb-lrzps
   - onap-contrib-netbox-app-f44957948-jczn6
   - onap-dcaegen2-dcae-bootstrap-5bc997c444-88j8p
   - onap-dcaegen2-dcae-dashboard-755449d876-pj2k8
   - onap-dcaegen2-dcae-deployment-handler-66986dbf7b-g8xwn
   - onap-dcaegen2-dcae-policy-handler-5c7bc7b7dd-gxktt
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-htp78
   - onap-dmaap-dmaap-bc-84cf999b96-c5vp4
   - onap-dmaap-dmaap-dr-node-0
   - onap-dmaap-dmaap-dr-prov-7f68c8f89-bx7zx
   - onap-dmaap-message-router-kafka-0
   - onap-dmaap-message-router-mirrormaker-7974bb7697-85f2p
   - onap-esr-esr-server-86b689bc5c-nf6xw
   - onap-multicloud-multicloud-694cf9c5bb-fmfs2
   - onap-multicloud-multicloud-windriver-575f4b56bf-8gfjn
   - onap-nbi-nbi-6d56b5b56b-vxsqp
   - onap-oof-oof-cmso-optimizer-769ffdd7d-hxkc5
   - onap-oof-oof-cmso-service-656c5dbfb5-njlrx
   - onap-oof-oof-d8f7dbfbf-5z7bw
   - onap-oof-oof-has-api-7b7f4c95b9-cqg7s
   - onap-oof-oof-has-controller-7db5bf5f8b-6xsgn
   - onap-oof-oof-has-data-8dc9c79dd-rcdfg
   - onap-oof-oof-has-reservation-589cc655f4-vvxg7
   - onap-oof-oof-has-solver-55d9849c69-cgrrv
   - onap-portal-portal-app-89686857d-s6w4v
   - onap-portal-portal-zookeeper-8586f7df94-jn265
   - onap-sdc-sdc-be-565dcfd9d-w658s
   - onap-sdc-sdc-dcae-be-85c669ddbf-hf6ms
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-rzfk8
   - onap-sdc-sdc-dcae-fe-5488b88f8c-4bfqg
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-h2nxz
   - onap-sdc-sdc-fe-694f4d7576-hs6q9
   - onap-sdc-sdc-kb-5b48c6fd44-d98lr
   - onap-sdc-sdc-onboarding-be-58f66544b6-94qjm
   - onap-sdc-sdc-onboarding-be-cassandra-init-mdmvc
   - onap-sdc-sdc-wfd-be-54ff7b9948-b5lzk
   - onap-sdc-sdc-wfd-fe-647d64468f-bfddm
   - onap-sdnc-network-name-gen-85ff6b896c-nbcw9
   - onap-sdnc-sdnc-0
   - onap-sdnc-sdnc-ansible-server-648f95867c-9d7lv
   - onap-sdnc-sdnc-dgbuilder-94dcbdf77-lxp6s
   - onap-sdnc-sdnc-dmaap-listener-86775f7769-5bnjt
   - onap-sdnc-sdnc-portal-6876fc8849-rj7q5
   - onap-sdnc-sdnc-ueb-listener-5dd8c464f9-phjlz
   - onap-so-so-6754c488f7-wqjzz
   - onap-so-so-bpmn-infra-8ddd4bb9f-5rdfs
   - onap-so-so-catalog-db-adapter-7ffb99cb84-5tp6b
   - onap-so-so-openstack-adapter-fd57d597b-jsmdl
   - onap-so-so-request-db-adapter-66bfcd8658-xpppn
   - onap-so-so-sdc-controller-5fd465cfcd-6j9wp
   - onap-so-so-vfc-adapter-5d99666cbc-bl7nh
   - onap-vfc-vfc-catalog-7467879cb6-wwffb
   - onap-vfc-vfc-nslcm-ccc867b6f-hqrwf
   - onap-vfc-vfc-vnflcm-5f79cb477d-vcl4l
   - onap-vfc-vfc-vnfmgr-77fccd68fd-5scbr
   - onap-vfc-vfc-vnfres-7f786df9d9-4qv6t
   - onap-vfc-vfc-workflow-engine-5ffdc84544-d282p
   - onap-vnfsdk-vnfsdk-7b5746d6cd-gsqk5]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc
   - onap-so]
******** Healthcheck Results *******
******** healthdist Results *******
2019-09-26 00:52:01,898 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f34b8b1a090>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1
Label: Verified=0