Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//96344-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 219
 * Nb Failed Pods: 57
 * List of Failed Pods: [
   - dep-dcae-prh-6f9d5b595d-4n9g4
   - dep-dcae-prh-6f9d5b595d-q5ljk
   - dep-dcae-prh-6f9d5b595d-x7n92
   - onap-aai-aai-babel-799f5b7675-6crhl
   - onap-aai-aai-babel-799f5b7675-72r92
   - onap-aai-aai-babel-799f5b7675-b9d5n
   - onap-aai-aai-babel-799f5b7675-bzwzh
   - onap-aai-aai-data-router-d6cbcbdb6-drv92
   - onap-aai-aai-resources-5955466f6f-jd9kr
   - onap-appc-appc-cdt-7645f5dcd7-7hkbg
   - onap-cds-cds-blueprints-processor-944878fb6-p7rz5
   - onap-cds-cds-command-executor-74dffcb87d-85w4n
   - onap-cds-cds-sdc-listener-75c5fd5ffb-qc98k
   - onap-clamp-clamp-dash-es-54644c6988-g55n9
   - onap-clamp-clamp-dash-logstash-7cf7884cdd-wwm9f
   - onap-dcaegen2-dcae-bootstrap-5bc997c444-vsw8t
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-xvjch
   - onap-esr-esr-server-86b689bc5c-hz4sc
   - onap-log-log-logstash-79f8f4f747-cn7hs
   - onap-multicloud-multicloud-694cf9c5bb-9g9jb
   - onap-multicloud-multicloud-694cf9c5bb-rv8hb
   - onap-multicloud-multicloud-694cf9c5bb-vkb6n
   - onap-multicloud-multicloud-starlingx-6fd97844cd-b67sx
   - onap-policy-brmsgw-8657875475-l8556
   - onap-policy-brmsgw-8657875475-p67ml
   - onap-policy-brmsgw-8657875475-wjhjq
   - onap-policy-brmsgw-8657875475-zzqgv
   - onap-policy-pap-585796947b-l6td8
   - onap-policy-pap-585796947b-n4g2g
   - onap-policy-pap-585796947b-z5ldx
   - onap-policy-policy-pap-f7cfc44b7-9pfjr
   - onap-policy-policy-xacml-pdp-6f7b74c8d-bxq27
   - onap-policy-policy-xacml-pdp-6f7b74c8d-q4btr
   - onap-policy-policy-xacml-pdp-6f7b74c8d-td4dq
   - onap-pomba-pomba-contextaggregator-6d9f9bb987-f89j7
   - onap-pomba-pomba-data-router-689596cff7-7g9b7
   - onap-pomba-pomba-data-router-689596cff7-tbns5
   - onap-pomba-pomba-data-router-689596cff7-xtxkc
   - onap-pomba-pomba-kibana-74f9c6b5cd-tgzc5
   - onap-pomba-pomba-sdncctxbuilder-9478c9bfc-j72vt
   - onap-pomba-pomba-sdncctxbuilder-9478c9bfc-k57q2
   - onap-pomba-pomba-sdncctxbuilder-9478c9bfc-l6dxn
   - onap-portal-portal-sdk-796fc8f8f5-mx5nd
   - onap-portal-portal-widget-84b4f7f448-2ggvk
   - onap-portal-portal-widget-84b4f7f448-bnlqf
   - onap-portal-portal-widget-84b4f7f448-kpfwb
   - onap-sdc-sdc-dcae-be-85c669ddbf-fbfk9
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-sljkk
   - onap-sdc-sdc-dcae-fe-5488b88f8c-kpwgh
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-swlkp
   - onap-sdc-sdc-fe-694f4d7576-vpw2z
   - onap-sdc-sdc-wfd-fe-647d64468f-s56c7
   - onap-sdnc-sdnc-dmaap-listener-86775f7769-dwfhd
   - onap-sdnc-sdnc-ueb-listener-5dd8c464f9-ptk9s
   - onap-vfc-vfc-nslcm-ccc867b6f-9jjl8
   - onap-vfc-vfc-nslcm-ccc867b6f-mjksr
   - onap-vfc-vfc-nslcm-ccc867b6f-nltqz]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 1
 * List of Failed Helm Charts: [
   - onap-dmaap]
******** Healthcheck Results *******
2019-09-27 23:49:58,664 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68ea4493d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68ea13ab90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f68ea13a150>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
403 != 200
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-contextaggregator.onap', port=9529): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68ea2893d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-fe.onap', port=9443): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f68ea08c990>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic CDS Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='cds-blueprints-processor-http.onap', port=8080): Max retries exceeded with url: /api/v1/execution-service/health-check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68e9f36b10>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 53 passed, 8 failed
61 tests total, 53 passed, 8 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
******** healthdist Results *******
2019-09-27 23:49:12,797 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
500 != 201

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0