Update patch set 2
Patch Set 2:

please check the below issue reported on this change, it could as well be false positive.

Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-catalog-db-adapter.onap', port=8082): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c9c4f5ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Patch-set: 2
Reviewer: Gerrit User 897 <897@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>