Update patch set 4
Patch Set 4:

Hi Max

Thank you so much for the patch to replace the AAI client with transactional client. After coming back from vacation I had to take care of a few urgent tasks internally. I noticed your patch had a +2 but due to merge conflict with other patches and dependency on my patch. 

I rebased my patch and squashed my patch and picked yours I was not able to push it due to the following error message:

Seems like gerrit permission issue. So I squashed your patch into mine. As result of squash If you rebase your patch with the latest patch set from mine you should see no changes.

Munir:so mahmad$ git push origin HEAD:refs/for/master
Counting objects: 57, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (42/42), done.
Writing objects: 100% (57/57), 27.57 KiB | 0 bytes/s, done.
Total 57 (delta 17), reused 20 (delta 4)
remote: Resolving deltas: 100% (17/17)
remote: Processing changes: refs: 1, done    
To https://gerrit.onap.org/r/so
 ! [remote rejected]     HEAD -> refs/for/master (not Signed-off-by author/committer/uploader in commit message footer)
error: failed to push some refs to 'https://mahmad@gerrit.onap.org/r/so'
Munir:so mahmad$

Patch-set: 4