Update patch set 1
Patch Set 1:

The error is due to 
ERROR: not able to provide the file [ManagedFile: id=so-settings, targetLocation=, variable=SETTINGS_FILE], can't be resolved by any provider - maybe it got deleted by an administrator

Patch-set: 1