Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//96263-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 198
 * Nb Failed Pods: 57
 * List of Failed Pods: [
   - onap-aai-aai-778d5bc98f-f9zm6
   - onap-aai-aai-sparky-be-68bcf7c4c-9szt2
   - onap-aai-aai-traversal-7f77cb867c-p95qw
   - onap-cds-cds-blueprints-processor-944878fb6-ls4sg
   - onap-cds-cds-command-executor-74dffcb87d-txgx6
   - onap-cds-cds-sdc-listener-75c5fd5ffb-7fmd9
   - onap-consul-consul-59d4b4ff5-ndfbf
   - onap-dcaegen2-dcae-dashboard-755449d876-dzx7s
   - onap-dcaegen2-dcae-deployment-handler-66986dbf7b-j5vxp
   - onap-dcaegen2-dcae-inventory-api-5c6b949bbf-gb8sq
   - onap-dcaegen2-dcae-policy-handler-5c7bc7b7dd-cwqp8
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-bk9tw
   - onap-dmaap-dmaap-dr-node-0
   - onap-dmaap-message-router-0
   - onap-dmaap-message-router-kafka-0
   - onap-dmaap-message-router-kafka-1
   - onap-dmaap-message-router-mirrormaker-7974bb7697-rmp6f
   - onap-oof-cmso-db-0
   - onap-oof-oof-cmso-optimizer-769ffdd7d-gr6v8
   - onap-oof-oof-cmso-service-656c5dbfb5-285pw
   - onap-oof-oof-d8f7dbfbf-f7j4k
   - onap-oof-oof-has-api-7b7f4c95b9-ph97t
   - onap-oof-oof-has-controller-7db5bf5f8b-nkbj5
   - onap-oof-oof-has-data-8dc9c79dd-q5xz5
   - onap-oof-oof-has-reservation-589cc655f4-b5gvv
   - onap-oof-oof-has-solver-55d9849c69-x7lwj
   - onap-pomba-pomba-contextaggregator-6d9f9bb987-mnz67
   - onap-portal-portal-cassandra-5c5cfdf59-nvz64
   - onap-sdc-sdc-be-565dcfd9d-pn8h9
   - onap-sdc-sdc-be-config-backend-kwdq4
   - onap-sdc-sdc-dcae-be-85c669ddbf-4qc2h
   - onap-sdc-sdc-dcae-be-tools-szt6h
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-gx6c7
   - onap-sdc-sdc-dcae-fe-5488b88f8c-b7skb
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-kspwm
   - onap-sdc-sdc-fe-694f4d7576-748rt
   - onap-sdc-sdc-kb-5b48c6fd44-jgtnq
   - onap-sdc-sdc-onboarding-be-58f66544b6-96488
   - onap-sdc-sdc-onboarding-be-cassandra-init-nr7dw
   - onap-sdc-sdc-wfd-be-54ff7b9948-28lmp
   - onap-sdc-sdc-wfd-fe-647d64468f-4n2mg
   - onap-sdnc-sdnc-dmaap-listener-86775f7769-qllxn
   - onap-sdnc-sdnc-ueb-listener-5dd8c464f9-gcpf8
   - onap-so-so-7c667c477f-5q5lw
   - onap-so-so-7c667c477f-9w6kd
   - onap-so-so-7c667c477f-h57xv
   - onap-so-so-7c667c477f-ll7s9
   - onap-so-so-7c667c477f-qj8gr
   - onap-so-so-7c667c477f-zhkh5
   - onap-so-so-catalog-db-adapter-68f58d5774-79xgb
   - onap-so-so-sdc-controller-59c6dd9bd4-csjhj
   - onap-vfc-vfc-catalog-7467879cb6-vgcjc
   - onap-vfc-vfc-generic-vnfm-driver-65c4d9f888-qzmqc
   - onap-vfc-vfc-nslcm-ccc867b6f-j9jhq
   - onap-vfc-vfc-vnflcm-5f79cb477d-rw4z9
   - onap-vfc-vfc-vnfmgr-77fccd68fd-qz9vr
   - onap-vfc-vfc-vnfres-7f786df9d9-xhtjj]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc]
******** Healthcheck Results *******
******** healthdist Results *******
2019-09-26 13:09:46,260 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6da3402090>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0