Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//97208-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 211
 * Nb Failed Pods: 36
 * List of Failed Pods: [
   - onap-aaf-aaf-sms-74975b77f-9km2t
   - onap-aai-aai-sparky-be-68bcf7c4c-zzf5s
   - onap-cds-cds-sdc-listener-75c5fd5ffb-qn288
   - onap-dcaegen2-dcae-dashboard-755449d876-6mhdn
   - onap-dcaegen2-dcae-deployment-handler-66986dbf7b-5p58q
   - onap-dcaegen2-dcae-policy-handler-5c7bc7b7dd-xshg2
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-nq9p6
   - onap-dmaap-message-router-mirrormaker-5bd5cbc745-qfmcv
   - onap-oof-oof-d8f7dbfbf-86jfz
   - onap-oof-oof-has-api-7b7f4c95b9-d9v89
   - onap-oof-oof-has-controller-7db5bf5f8b-mnc2q
   - onap-oof-oof-has-data-8dc9c79dd-lxlhc
   - onap-oof-oof-has-reservation-589cc655f4-2krwx
   - onap-oof-oof-has-solver-55d9849c69-w9rzj
   - onap-sdc-sdc-be-8485bc5558-nmzbk
   - onap-sdc-sdc-be-config-backend-2rdkp
   - onap-sdc-sdc-dcae-be-85c669ddbf-b24m8
   - onap-sdc-sdc-dcae-be-tools-2mg92
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-8dc5m
   - onap-sdc-sdc-dcae-fe-5488b88f8c-qgkjr
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-56cdq
   - onap-sdc-sdc-fe-5cfcddf448-548fp
   - onap-sdc-sdc-kb-5b48c6fd44-fpbnx
   - onap-sdc-sdc-onboarding-be-8c84cb794-m665f
   - onap-sdc-sdc-onboarding-be-cassandra-init-trsg6
   - onap-sdc-sdc-wfd-be-54ff7b9948-bwzcx
   - onap-sdc-sdc-wfd-be-workflow-init-lm5l5
   - onap-sdc-sdc-wfd-fe-647d64468f-5pcx9
   - onap-sdnc-sdnc-ueb-listener-5d78c9c586-kmmnk
   - onap-so-so-bpmn-infra-87d8f7dd7-6c2x4
   - onap-so-so-catalog-db-adapter-85954d6564-895rm
   - onap-so-so-cbd7f9d65-d65q8
   - onap-so-so-openstack-adapter-8686dd8cbd-2drgr
   - onap-so-so-request-db-adapter-57664d4c5d-l2x77
   - onap-so-so-sdc-controller-6774bbd9b6-8sz62
   - onap-so-so-vfc-adapter-55ff4bb6b7-62544]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc
   - onap-so]
******** Healthcheck Results *******
******** healthdist Results *******
2019-10-16 21:47:05,806 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd940119090>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0