Update patch set 3
Patch Set 3:

Please check the below issue reported by the gating on this change.


Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-catalog-db-adapter.onap', port=8082): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c07cfb5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Patch-set: 3
Reviewer: Gerrit User 897 <897@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>